name: Build Electron Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - name: Install
        run: npm ci

      - name: Build portable executable
        run: npm run make:portable

      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/*.exe
          fail_on_unmatched_files: true
          generate_release_notes: true
